language: ruby

rvm:
  - '1.8.7'
  - '2.6.3'

gemfile:
  - 'Gemfile'

dist: trusty

install:
  # Replace default Travis CI bundler script with a version that doesn't
  # explode when lockfile doesn't match recently bumped version
  - bundle install --no-deployment --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

script: bundle exec rake
