#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)

require 'geordi/util'

Geordi::Util.installing_missing_gems do
  require 'rubygems' unless defined?(Gem)
  require 'geordi'
  require 'thor'

  Geordi::CLI.start
end
